Create a DiningCommonsService and related controller method for fetching the names of all dining commons
ucsb-cs156-f24/proj-dining-f24-14 pull request #56
Opened 2024-11-19 02:40 UTC by Va1a

Closes #44 
Dokku Deployment (for #56, #61, #62, #63): https://pd-consolidated-1.dokku-14.cs.ucsb.edu/

This resolves a subissue which is part of the epic "Home page lists dining commons and has a link to each"

In this PR, we implement DiningCommonsService.java , a Springboot service file that as of now allows us to access the UCSB dining commons API to fetch data from the following endpoint: /names. This endpoint returns the names and codes of all the dining commons at UCSB.
**Additionally, I added the following line to the application properties file:**
`app.ucsb.api.consumer_key=${UCSB_API_KEY:${env.UCSB_API_KEY:see-instructions-in-readme}}`
This allows us to define the UCSB_API_KEY in the .env file, so that it can be used within the application. This also means that the key NEEDS to be defined in the .env file (or as an env var) for proper functionality.

I also made a test file for DiningCommonsService. This gives us full test coverage and mutation coverage for the Service class implementation.
Finally, I created the DiningCommonsController file and added the following GET endpoint: "/api/diningcommons" which returns the name of all the dining commons as returned by the UCSB api.

2024-11-19 21:10 UTC, pconrad requested changes
A couple of lines that you might consider removing.  Other than that, looks really good.

2024-11-19 21:10 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/DiningCommonsController.java
> +  @Autowired UserRepository userRepository;
Why do you need the UserRepository in this controller?  If you don't need it, remove it.

2024-11-19 21:10 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/DiningCommonsController.java
> +  private ObjectMapper mapper = new ObjectMapper();
Are we using the mapper anywhere?  If not, consider removing it.

2024-11-19 21:55 UTC, amanpdesai approved these changes
Looks good to me!

2024-11-20 01:52 UTC, amanpdesai submitted a review, later dismissed
Looks good to me!

2024-11-23 19:33 UTC, pconrad approved these changes
Code LGTM, but there is no dokku deployment on which to test.  Please fix that.

2024-11-25 00:08 UTC, pconrad commented
On this PR: I'm testing on https://pd-consolidated-1.dokku-14.cs.ucsb.edu/ and two of the three new endpoints are working, while one is not working.

Is there something I'm doing wrong?

# Details

## The ones that work

`GET https://pd-consolidated-1.dokku-14.cs.ucsb.edu/api/diningcommons/all` works:

<img width="1165" alt="image" src="https://github.com/user-attachments/assets/42d62500-6ac8-4bd0-8698-3677c14225ce">

`GET https://pd-consolidated-1.dokku-14.cs.ucsb.edu/api/diningcommons/2024-11-24T00%3A00%3A00/de-la-guerra` works:

<img width="746" alt="image" src="https://github.com/user-attachments/assets/0958b068-b0fe-4348-9758-14f8111f6735">

## The one that's not working

But the third one, the one that gets the menu items, is not working for me.  Am I just using bad values?

`GET https://pd-consolidated-1.dokku-14.cs.ucsb.edu/api/diningcommons/2024-11-24T00%3A00%3A00/dinner/de-la-guerra`

<img width="735" alt="image" src="https://github.com/user-attachments/assets/a5075cf8-96dc-4a8d-a6ff-f141e2da44f5">

2024-11-25 00:12 UTC, pconrad approved these changes
LGTM

2024-11-25 00:16 UTC, merged