Review backend 3
ucsb-cs156-f24/proj-dining-f24-14 pull request #66
Opened 2024-11-21 02:25 UTC by kev-yan

2024-11-25 08:02 UTC, Va1a submitted a review, later dismissed
LGTM

2024-11-29 19:09 UTC, pconrad requested changes
This PR appears to have many of the same problems as PR #55 so I don't see a point in rehashing all of those points here.

Fix PR55, and incorporate those changes into this PR, and make sure there is a thorough team code review that takes into account ALL of the prior feedback on PR55 and this one, as well as actually looking at the PR checklist.

2024-12-01 23:28 UTC, amanpdesai approved these changes, later dismissed
LGTM

2024-12-02 06:11 UTC, pconrad commented on pom.xml
> +    </dependency>
This appears to be to support:

```
import org.apache.commons.lang3.time.DateFormatUtils;
```

But it wasn't clear if you are actually using DateFormatUtils anywhere in this code.

So could you remove this change to the pom.xml as well as the unnecessary import?

2024-12-02 06:14 UTC, pconrad requested changes

2024-12-02 06:14 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/ReviewsController.java
> +import org.apache.commons.lang3.time.DateFormatUtils;
Is this import used anywhere?  If not, can it be removed?

2024-12-02 06:14 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/ExampleApplication.java
> +@EnableAsync  // @EnableJpaAuditing(dateTimeProviderRef = "utcDateTimeProvider") doesn't work with mvn tests but works with backend
Can we clean this up?

We don't put commented out code in PRs that are merged into main.

2024-12-02 06:16 UTC, pconrad requested changes
Can we remove the unnecessary changes to pom.xml, the unused import, and the commented out code?

2024-12-02 20:40 UTC, Va1a submitted a review, later dismissed
CR changes addressed, lgtm.

2024-12-02 20:46 UTC, Va1a submitted a review, later dismissed
Straggling comments removed, lgtm.

2024-12-02 21:13 UTC, Va1a approved these changes
merge conflicts fixed

2024-12-02 23:43 UTC, pconrad approved these changes
LGTM

2024-12-02 23:43 UTC, merged